config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :vehicles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :vehicle
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home", only: [:index]
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]
  layout "home", only: [:index]
  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.includes(:vehicle).where(user_id: current_user.id, active: true)
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservations_url, notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservations_url, notice: "Reservation was successfully created." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:vehicle_id, :active, :total_price, :user_id, :qualification, :hours_reservation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "auth", only: [:new, :edit]

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show ]
  layout "auth", only: [:new]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :address, :password, :password_confirmation)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[ show ]
  layout "home", only: [:index, :show]

  # GET /vehicles or /vehicles.json
  def index
    @reservations = Reservation.where(active: true).group(:vehicle_id).to_a
    @ids = []
    @reservations.map { |reservation| @ids.push(reservation.vehicle_id) }
    @vehicles = Vehicle.where.not(id: @ids)
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:name, :image, :description, :model, :value_per_hour)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/home/index.html.erb
<style>
    /*
   * Globals
   */


    /* Custom default button */
    .btn-secondary,
    .btn-secondary:hover,
    .btn-secondary:focus {
        color: #333;
        text-shadow: none; /* Prevent inheritance from `body` */
    }


    /*
     * Base structure
     */



    /*
     * Header
     */

    .nav-masthead .nav-link {
        padding: .25rem 0;
        font-weight: 700;
        color: rgba(0, 0, 0, 0.5);
        background-color: transparent;
        border-bottom: .25rem solid transparent;
    }

    .nav-masthead .nav-link:hover,
    .nav-masthead .nav-link:focus {
        border-bottom-color: rgba(255, 255, 255, .25);
    }

    .nav-masthead .nav-link + .nav-link {
        margin-left: 1rem;
    }

    .nav-masthead .active {
        color: #fff;
        border-bottom-color: #fff;
    }
    header {
        box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
    }
    .text-header {
        text-shadow: 0 .03rem .1rem rgba(0, 0, 0, .5);
    }
</style>
<% if notice %>
<div class="alert alert-info" role="alert" id="notice">
  <%= notice %>
</div>
<% end %>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<%= image_path('home.jpg') %>" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block position-absolute top-50 start-50 translate-middle">
        <h1 class="text-header">Car Hire – Search, Compare & Save</h1>
        <p class="lead">
          <%= link_to "View vehicles", vehicles_path , class: "btn btn-primary btn-lg fw-bold"  %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarRental</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarRental</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="text-center" style="background-image: url('<%= image_path('sign_in.jpg') %>'); background-size: cover">
<%= yield %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html class="h-100">
<head>
  <title>CarRental</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Car Rental</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path , class: "nav-link active"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Vehicles", vehicles_path , class: "nav-link"  %>
        </li>
        <% if current_user %>
        <li class="nav-item">
          <%= link_to "Reservations", reservations_path , class: "nav-link"  %>
        </li>
        <% end %>
      </ul>
      <ul class="d-flex navbar-nav">
        <% if current_user %>
          <li class="nav-item">
            <span class="mx-2 py-1"><%= current_user.email %></span>
            <%= link_to "Log Out", logout_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", login_path , class: "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path , class: "nav-link"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<%= yield %>
</body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :vehicle_id, style: "display: block" %>
    <%= form.text_field :vehicle_id %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.label :total_price, style: "display: block" %>
    <%= form.text_field :total_price %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :qualification, style: "display: block" %>
    <%= form.number_field :qualification %>
  </div>

  <div>
    <%= form.label :hours_reservation, style: "display: block" %>
    <%= form.number_field :hours_reservation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div class="col" id="<%= dom_id reservation %>">
  <div class="card shadow-sm">
    <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="<%= reservation.vehicle.image %>" alt="">
    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <h4><%= reservation.vehicle.name %> <span class="badge bg-secondary"><%= reservation.vehicle.model %></span></h4>
          </div>
          <div class="col-12">
            <div class="row">
              <div class="col-12">
                <strong>Hours reservation:</strong>
                <%= reservation.hours_reservation %>
              </div>
              <div class="col-12">
                <strong>Status:</strong>
                <% if reservation.active %>
                <span class="badge bg-success">Active</span>
                <% else %>
                <span class="badge bg-danger">Inactive</span>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-12">
            <p class="text-end fs-5 fw-lighter m-0"><strong>Total:</strong><span class="fw-bold fs-3">$<%= reservation.total_price %></span>USD</p>
          </div>
          <div class="col-12 text-center">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#qualificationModal"
            onclick="changeReservation(<%= reservation.id %>)">
              Finish
            </button>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <p class="m-2 p-2"></p>
    </div>
    <div class="col-12">
      <p style="color: green"><%= notice %></p>
      <main>
        <div class="album py-5">
          <div class="container">
            <h1 class="text-center">Reservations</h1>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id="vehicles">
              <% @reservations.each do |reservation| %>
                <%= render reservation %>
              <% end %>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="qualificationModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Service Qualification</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with url: "/reservations/", method: :put, local: true, id: "form_reservation" do %>
        <input type="hidden" name="reservation[qualification]" id="qualification" value="">
        <input type="hidden" name="reservation[active]" value="false">
        <div class="modal-body text-center">
          <i class="bi bi-star" id="star1"></i>
          <i class="bi bi-star" id="star2"></i>
          <i class="bi bi-star" id="star3"></i>
          <i class="bi bi-star" id="star4"></i>
          <i class="bi bi-star" id="star5"></i>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <%= submit_tag("Finish",class: 'btn btn-primary') %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    function changeReservation(id_value){
        let id = id_value;
        document.getElementById("form_reservation").action = "/reservations/"+id;
        const star1 = document.querySelector("#star1");
        const star2 = document.querySelector("#star2");
        const star3 = document.querySelector("#star3");
        const star4 = document.querySelector("#star4");
        const star5 = document.querySelector("#star5");

        star1.addEventListener("click", (event) => {
            event.preventDefault();
            id = 1;
            star1.classList.remove("bi-star");
            star1.classList.add("bi-star-fill");
            star2.classList.remove("bi-star-fill");
            star2.classList.add("bi-star");
            star3.classList.remove("bi-star-fill");
            star3.classList.add("bi-star");
            star4.classList.remove("bi-star-fill");
            star4.classList.add("bi-star");
            star5.classList.remove("bi-star-fill");
            star5.classList.add("bi-star");
            document.querySelector("#qualification").value = 1;
        });
        star2.addEventListener("click", (event) => {
            event.preventDefault();
            id = 2;
            star1.classList.remove("bi-star");
            star1.classList.add("bi-star-fill");
            star2.classList.remove("bi-star");
            star2.classList.add("bi-star-fill");
            star3.classList.remove("bi-star-fill");
            star3.classList.add("bi-star");
            star4.classList.remove("bi-star-fill");
            star4.classList.add("bi-star");
            star5.classList.remove("bi-star-fill");
            star5.classList.add("bi-star");
            document.querySelector("#qualification").value = 2;
        });
        star3.addEventListener("click", (event) => {
            event.preventDefault();
            id = 3;
            star1.classList.remove("bi-star");
            star1.classList.add("bi-star-fill");
            star2.classList.remove("bi-star");
            star2.classList.add("bi-star-fill");
            star3.classList.remove("bi-star");
            star3.classList.add("bi-star-fill");
            star4.classList.remove("bi-star-fill");
            star4.classList.add("bi-star");
            star5.classList.remove("bi-star-fill");
            star5.classList.add("bi-star");
            document.querySelector("#qualification").value = 3;
        });
        star4.addEventListener("click", (event) => {
            event.preventDefault();
            id = 4;
            star1.classList.remove("bi-star");
            star1.classList.add("bi-star-fill");
            star2.classList.remove("bi-star");
            star2.classList.add("bi-star-fill");
            star3.classList.remove("bi-star");
            star3.classList.add("bi-star-fill");
            star4.classList.remove("bi-star");
            star4.classList.add("bi-star-fill");
            star5.classList.remove("bi-star-fill");
            star5.classList.add("bi-star");
            document.querySelector("#qualification").value = 4;
        });
        star5.addEventListener("click", (event) => {
            event.preventDefault();
            id = 5;
            star1.classList.remove("bi-star");
            star1.classList.add("bi-star-fill");
            star2.classList.remove("bi-star");
            star2.classList.add("bi-star-fill");
            star3.classList.remove("bi-star");
            star3.classList.add("bi-star-fill");
            star4.classList.remove("bi-star");
            star4.classList.add("bi-star-fill");
            star5.classList.remove("bi-star");
            star5.classList.add("bi-star-fill");
            document.querySelector("#qualification").value = 5;
        });
    }
</script>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit this reservation", edit_reservation_path(@reservation) %> |
  <%= link_to "Back to reservations", reservations_path %>

  <%= button_to "Destroy this reservation", @reservation, method: :delete %>
</div>

app/views/users/_form.html.erb
 <%= form_with(model: user) do |form| %>
    <div class="row">
      <% if user.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="col-12">
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="col-12">
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <div class="col-12">
        <%= form.label :phone, style: "display: block" %>
        <%= form.text_field :phone, class: "form-control" %>
      </div>

      <div class="col-12">
        <%= form.label :address, style: "display: block" %>
        <%= form.text_field :address, class: "form-control" %>
      </div>

      <div class="col-6">
        <%= form.label :password, style: "display: block" %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="col-6">
        <%= form.label :password_confirmation, style: "display: block" %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="col-12">
        <hr class="my-4">
        <%= form.submit class: "w-100 btn btn-primary btn-lg" %>
      </div>
    </div>
  <% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<style>
    .container {
        max-width: 960px;
    }
</style>
<div class="container pt-3">
    <div class="card bg-white bg-opacity-75">
      <div class="card-body">
        <main>
          <div class="py-3 text-center">
            <h2>New user</h2>
          </div>

          <div class="row g-5">
            <div class="col-md-12">
              <%= render "form", user: @user %>
            </div>
          </div>
        </main>
        <footer class="my-1 pt-5 text-muted text-center text-small">
          <p class="mb-1">&copy; 2022 Car Rental</p>
          <ul class="list-inline">
            <%= link_to "Home", root_path %>
          </ul>
        </footer>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/vehicles/_vehicle.html.erb
<div class="col" id="<%= dom_id vehicle %>">
  <%= link_to(vehicle, class: "text-decoration-none text-black") do %>
    <div class="card shadow-sm">
      <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="<%= vehicle.image %>" alt="">
      <div class="card-body">
        <h4><%= vehicle.name %> <span class="badge bg-secondary"><%= vehicle.model %></span></h4>
        <p class="text-end fs-5 fw-lighter m-0"><span class="fw-bold fs-3">$<%= vehicle.value_per_hour %></span>USD/H</p>
      </div>
    </div>
  <% end %>
</div>

app/views/vehicles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <p class="m-2 p-2"></p>
    </div>
    <div class="col-12">
      <p style="color: green"><%= notice %></p>
      <main>
        <div class="album py-5">
          <div class="container">
            <h1 class="text-center">Vehicles</h1>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id="vehicles">
              <% @vehicles.each do |vehicle| %>
                <%= render vehicle %>
              <% end %>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <p class="m-4 p-4"></p>
    </div>
    <% if notice %>
    <div class="col-12">
      <div class="alert alert-info" role="alert">
        <%= notice %>
      </div>
    </div>
    <% end %>
    <div class="col-12 col-md-6">
      <img src="<%= @vehicle.image %>" class="img-fluid rounded" alt="">
    </div>
    <div class="col-12 col-md-6">
      <h1><%= @vehicle.name %></h1>
      <p><%= @vehicle.description %></p>
      <p class="text-end fs-5 fw-lighter m-0"><span class="fw-bold fs-3">$<%= @vehicle.value_per_hour %></span>USD/H</p>
      <div class="d-grid gap-2">
        <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">Rent</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Reserve Car</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with url: reservations_path, method: :post, local: true do %>
        <div class="modal-body">
          <% if current_user %>
            Hours
            <input type="hidden" name="reservation[user_id]" value="<%= current_user.id %>">
            <input type="hidden" name="reservation[vehicle_id]" value="<%= @vehicle.id %>">
            <input type="hidden" name="reservation[active]" value="true">
            <input type="hidden" name="reservation[total_price]" id="total_price" value="<%= @vehicle.value_per_hour %>">
            <input type="number" name="reservation[hours_reservation]" id="hours" value="1">
            <p class="text-end fs-5 fw-lighter m-0"><span class="fw-bold fs-3">$<%= @vehicle.value_per_hour %></span>USD/H</p>
            <hr>
            <h2>Total</h2>
            <p class="text-end fs-5 fw-lighter m-0"><span class="fw-bold fs-3" id="total">$<%= @vehicle.value_per_hour %></span>USD</p>
          <% else %>
            You must log in
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <% if current_user %>
            <%= submit_tag("Reserve",class: 'btn btn-primary') %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    document.querySelector("#hours").addEventListener("change", (event) => {
        let price = <%= @vehicle.value_per_hour %>;
        event.preventDefault();
        console.log(document.querySelector("#hours"))
        document.querySelector("#total_price").value = parseFloat(parseFloat(document.querySelector("#hours").value ? document.querySelector("#hours").value: 0) * price);
        document.querySelector("#total").innerHTML = '$' + parseFloat(parseFloat(document.querySelector("#hours").value ? document.querySelector("#hours").value: 0) * price);
    });
</script>

<!--<div>
  <%#= link_to "Edit this vehicle", edit_vehicle_path(@vehicle) %> |
  <%#= link_to "Back to vehicles", vehicles_path %>

  <%#= button_to "Destroy this vehicle", @vehicle, method: :delete %>
</div>-->